name: qtcreator
title: Qt Creator
base: core22
adopt-info: qtcreator
summary: Qt Creator

grade: stable
confinement: classic

parts:

  # install mesa with 'no-patchelf' for DRI drivers
  # https://forum.snapcraft.io/t/opengl-broken-in-classic-core20-snap-on-22-04/29401/2
  mesa-patchelf:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    build-attributes:
    - enable-patchelf
    stage:
    - -usr/lib/${CRAFT_ARCH_TRIPLET}/dri

  mesa-no-patchelf:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    build-attributes:
    - no-patchelf
    stage:
    - usr/lib/${CRAFT_ARCH_TRIPLET}/dri

  qtcreator:
    parse-info: [usr/share/metainfo/org.qt-project.qtcreator.appdata.xml]
    plugin: nil
    build-attributes:
    - enable-patchelf
    stage-packages:
    - qtcreator

apps:
  qtcreator-ros:
    command: usr/bin/qtcreator
    common-id: org.qt-project.qtcreator.desktop
    desktop: usr/share/applications/org.qt-project.qtcreator.desktop
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}
      # LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/dri
      QT_QPA_PLATFORM: wayland;xcb
