name: qtcreator
title: Qt Creator
base: core22
adopt-info: qtcreator
summary: Qt Creator

grade: stable
confinement: classic

parts:

  # install mesa with 'no-patchelf' for DRI drivers
  # https://forum.snapcraft.io/t/opengl-broken-in-classic-core20-snap-on-22-04/29401/2
  mesa-patchelf:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    build-attributes:
    - enable-patchelf
    stage:
    - -usr/lib/${CRAFT_ARCH_TRIPLET}/dri

  mesa-no-patchelf:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    build-attributes:
    - no-patchelf
    stage:
    - usr/lib/${CRAFT_ARCH_TRIPLET}/dri

  qtcreator:
    source: http://code.qt.io/qt-creator/qt-creator.git
    source-tag: v10.0.0
    source-depth: 1
    parse-info: [usr/local/share/metainfo/org.qt-project.qtcreator.appdata.xml]
    plugin: cmake
    cmake-generator: Ninja
    build-attributes:
    - enable-patchelf
    build-packages:
    - qt6-base-dev
    - qt6-base-private-dev
    - qt6-wayland-dev
    - qt6-declarative-dev
    - libqt6core5compat6-dev
    - libegl-dev
    - libgl-dev
    - libdw-dev
    stage-packages:
    - libqt6concurrent6
    - libqt6core6
    - libqt6printsupport6
    - libqt6sql6
    - libqt6test6
    - libqt6widgets6
    - libqt6xml6
    - libqt6core5compat6
    - qt6-qpa-plugins
    - qt6-wayland
    - libdw1

apps:
  qtcreator:
    command: usr/local/bin/qtcreator
    common-id: org.qt-project.qtcreator.desktop
    desktop: usr/local/share/applications/org.qt-project.qtcreator.desktop
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/local/lib:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/dri
      QT_QPA_PLATFORM: wayland;xcb
