name: qtcreator-ros
title: Qt Creator
base: core24
adopt-info: qtcreator
icon: snap/gui/qtcreator-ros.svg
summary: Qt Creator with ROS plugin

grade: stable
confinement: classic

parts:

  # install mesa with 'no-patchelf' for DRI drivers
  # https://forum.snapcraft.io/t/opengl-broken-in-classic-core20-snap-on-22-04/29401/2
  mesa-patchelf:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    build-attributes:
    - enable-patchelf
    stage:
    - -usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri

  mesa-no-patchelf:
    plugin: nil
    stage-packages:
    - libgl1-mesa-dri
    build-attributes:
    - no-patchelf
    stage:
    - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri

  qt6:
    source: http://code.qt.io/qt/qt5.git
    source-branch: "6.2.4"
    source-depth: 1
    source-submodules: [qt5compat,qtbase,qtdeclarative,qtquick3d,qtserialport,qtshadertools,qtsvg,qttools,qtwayland]
    plugin: cmake
    cmake-generator: Ninja
    build-attributes:
    - enable-patchelf
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
    - libegl-dev
    - libgl-dev
    - libharfbuzz-dev
    - libjpeg-dev
    - libpng-dev
    - libvulkan-dev
    - libwayland-dev
    # xcb QPA (Qt Platform Abstraction) platform plugin
    - libfontconfig1-dev
    - libfreetype6-dev
    - libx11-dev
    - libx11-xcb-dev
    - libxext-dev
    - libxfixes-dev
    - libxi-dev
    - libxrender-dev
    - libxcb1-dev
    - libxcb-glx0-dev
    - libxcb-keysyms1-dev
    - libxcb-image0-dev
    - libxcb-shm0-dev
    - libxcb-icccm4-dev
    - libxcb-sync-dev
    - libxcb-xfixes0-dev
    - libxcb-shape0-dev
    - libxcb-randr0-dev
    - libxcb-render-util0-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    stage-packages:
    - libegl1
    - libfontconfig1
    - libfreetype6
    - libgl1
    - libglvnd0
    - libglx0
    - libgraphite2-3
    - libharfbuzz0b
    - libjpeg-turbo8
    - libpcre2-16-0
    - libpng16-16
    - libwayland-cursor0
    - libwayland-egl1
    - libx11-6
    - libx11-xcb1
    - libxau6
    - libxcb-glx0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-render0
    - libxcb-shape0
    - libxcb-shm0
    - libxcb-sync1
    - libxcb-util1
    - libxcb-xfixes0
    - libxcb-xkb1
    - libxcb1
    - libxdmcp6
    - libxkbcommon-x11-0
    - libxkbcommon0

  qtcreator:
    after: [qt6]
    source: http://code.qt.io/qt-creator/qt-creator.git
    source-tag: v13.0.2
    source-depth: 1
    parse-info: [share/metainfo/org.qt-project.qtcreator.appdata.xml]
    plugin: cmake
    cmake-generator: Ninja
    build-attributes:
    - enable-patchelf
    override-build: |
      cmake -S ${CRAFT_PART_SRC} -B ${CRAFT_PART_BUILD} -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CRAFT_PART_INSTALL}
      cmake --build ${CRAFT_PART_BUILD}
      cmake --install ${CRAFT_PART_BUILD}
      cmake --install ${CRAFT_PART_BUILD} --component Devel
    build-environment:
    - LD_LIBRARY_PATH: ${CRAFT_STAGE}/lib
    build-packages:
    - libdw-dev
    stage-packages:
    - libdw1
    - libyaml-cpp0.8

  plugin-ros:
    after: [qtcreator]
    source: https://github.com/ros-industrial/ros_qtc_plugin.git
    source-tag: "13.1"
    source-depth: 1
    plugin: cmake
    cmake-generator: Ninja
    build-attributes:
    - enable-patchelf
    cmake-parameters:
    - -DCMAKE_INSTALL_PREFIX=/
    build-environment:
    - LD_LIBRARY_PATH: ${CRAFT_STAGE}/lib
    # using CMAKE_INSTALL_PREFIX=/ will install to /usr/local/ nevertheless
    override-prime: |
      craftctl default
      cp -r ${CRAFT_PRIME}/usr/lib/qtcreator/* ${CRAFT_PRIME}/lib/qtcreator/
      rm -r ${CRAFT_PRIME}/usr/lib/qtcreator/
      cp -r ${CRAFT_PRIME}/usr/share/qtcreator/* ${CRAFT_PRIME}/share/qtcreator/
      rm -r ${CRAFT_PRIME}/usr/share/qtcreator/
    build-packages:
    - libyaml-cpp-dev
    stage-packages:
    - libyaml-cpp0.8

  launchers:
    after: [qtcreator]
    plugin: nil
    override-prime: |
      sed -i -e 's|Name=Qt Creator|Name=Qt Creator ROS|g' share/applications/org.qt-project.qtcreator.desktop
      sed -i -e 's|Icon=QtProject-qtcreator|Icon=${SNAP}/meta/gui/qtcreator-ros.svg|g' share/applications/org.qt-project.qtcreator.desktop

  cleanup:
    after: [launchers]
    plugin: nil
    override-prime: |
      shopt -s extglob
      rm -v bin/!("qtcreator"|"qtcreator.sh")
      rm -r {doc,etc,include}
      rm -r lib/{cmake,metatypes,objects-Release,qtcreator/objects-Release}
      rm lib/*.prl
      rm -v libexec/!("qtcreator")
      rm -r {modules,qml}
      rm -r share/qtcreator/{HACKING,LICENSE.GPL3-EXCEPT,README.md}
      rm -r usr/share/{doc,doc-base,drirc.d,man,pkgconfig}
      shopt -u extglob

apps:
  qtcreator-ros:
    command: bin/qtcreator
    common-id: org.qt-project.qtcreator.desktop
    desktop: share/applications/org.qt-project.qtcreator.desktop
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri
      QT_QPA_PLATFORM: wayland;xcb
